apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylladb
  namespace: scylla
spec:
  version: "2026.1.3"
  agentVersion: "3.5.0"
  developerMode: false
  datacenter:
    name: dc1
    racks:
    - name: us-east-1a
      members: 1
      scyllaConfig: scylla-config
      storage: { capacity: 100Gi, storageClassName: scylladb-gp3 }
      resources:
        requests: { cpu: 3, memory: 24Gi }
        limits:   { cpu: 3, memory: 24Gi }
      placement:
        tolerations:
        - { key: scylla.scylladb.com/dedicated, operator: Equal, value: "true", effect: NoSchedule }
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - { key: topology.kubernetes.io/zone, operator: In, values: ["us-east-1a"] }
    - name: us-east-1b
      members: 2
      scyllaConfig: scylla-config
      storage: { capacity: 100Gi, storageClassName: scylladb-gp3 }
      resources:
        requests: { cpu: 3, memory: 24Gi }
        limits:   { cpu: 3, memory: 24Gi }
      placement:
        tolerations:
        - { key: scylla.scylladb.com/dedicated, operator: Equal, value: "true", effect: NoSchedule }
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - { key: topology.kubernetes.io/zone, operator: In, values: ["us-east-1b"] }
    - name: us-east-1c
      members: 1
      scyllaConfig: scylla-config
      storage: { capacity: 100Gi, storageClassName: scylladb-gp3 }
      resources:
        requests: { cpu: 3, memory: 24Gi }
        limits:   { cpu: 3, memory: 24Gi }
      placement:
        tolerations:
        - { key: scylla.scylladb.com/dedicated, operator: Equal, value: "true", effect: NoSchedule }
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - { key: topology.kubernetes.io/zone, operator: In, values: ["us-east-1c"] }