name: ScyllaDB backup to S3

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: scylla-assessment
  NS: scylla
  KEYSPACE: demo
  BUCKET: chaithu-backup-scylla
  POD: scylladb-dc1-us-east-1a-0

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (keyless via OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::719982589414:role/gha-scylla
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name "$CLUSTER_NAME" --region "$AWS_REGION"

      - name: Run backup
        run: |
          chmod +x scripts/backup.sh
          NS="$NS" KEYSPACE="$KEYSPACE" BUCKET="$BUCKET" POD="$POD" ./scripts/backup.sh
